// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_rspdlite_RCPPEXPORTS_H_GEN_
#define RCPP_rspdlite_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace rspdlite {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("rspdlite", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("rspdlite", "_rspdlite_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in rspdlite");
            }
        }
    }

    inline std::string formatter(const std::string s, std::vector<std::string> v) {
        typedef SEXP(*Ptr_formatter)(SEXP,SEXP);
        static Ptr_formatter p_formatter = NULL;
        if (p_formatter == NULL) {
            validateSignature("std::string(*formatter)(const std::string,std::vector<std::string>)");
            p_formatter = (Ptr_formatter)R_GetCCallable("rspdlite", "_rspdlite_formatter");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_formatter(Shield<SEXP>(Rcpp::wrap(s)), Shield<SEXP>(Rcpp::wrap(v)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<std::string >(rcpp_result_gen);
    }

}

#endif // RCPP_rspdlite_RCPPEXPORTS_H_GEN_
