// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// formatter
std::string formatter(const std::string s, std::vector<std::string> v);
RcppExport SEXP _rspdlite_formatter(SEXP sSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type s(sSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(formatter(s, v));
    return rcpp_result_gen;
END_RCPP
}
// trace_
void trace_(std::string s);
RcppExport SEXP _rspdlite_trace_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    trace_(s);
    return R_NilValue;
END_RCPP
}
// debug_
void debug_(std::string s);
RcppExport SEXP _rspdlite_debug_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    debug_(s);
    return R_NilValue;
END_RCPP
}
// info_
void info_(std::string s);
RcppExport SEXP _rspdlite_info_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    info_(s);
    return R_NilValue;
END_RCPP
}
// warn_
void warn_(std::string s);
RcppExport SEXP _rspdlite_warn_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    warn_(s);
    return R_NilValue;
END_RCPP
}
// error_
void error_(std::string s);
RcppExport SEXP _rspdlite_error_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    error_(s);
    return R_NilValue;
END_RCPP
}
// critical_
void critical_(std::string s);
RcppExport SEXP _rspdlite_critical_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    critical_(s);
    return R_NilValue;
END_RCPP
}
// set_level_
void set_level_(std::string s);
RcppExport SEXP _rspdlite_set_level_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    set_level_(s);
    return R_NilValue;
END_RCPP
}
// get_level_
std::string get_level_();
RcppExport SEXP _rspdlite_get_level_() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_level_());
    return rcpp_result_gen;
END_RCPP
}
// set_name_
void set_name_(const std::string& s);
RcppExport SEXP _rspdlite_set_name_(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type s(sSEXP);
    set_name_(s);
    return R_NilValue;
END_RCPP
}
// get_name_
std::string get_name_();
RcppExport SEXP _rspdlite_get_name_() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_name_());
    return rcpp_result_gen;
END_RCPP
}
// cppstandard
int cppstandard();
RcppExport SEXP _rspdlite_cppstandard() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cppstandard());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rspdlite_formatter", (DL_FUNC) &_rspdlite_formatter, 2},
    {"_rspdlite_trace_", (DL_FUNC) &_rspdlite_trace_, 1},
    {"_rspdlite_debug_", (DL_FUNC) &_rspdlite_debug_, 1},
    {"_rspdlite_info_", (DL_FUNC) &_rspdlite_info_, 1},
    {"_rspdlite_warn_", (DL_FUNC) &_rspdlite_warn_, 1},
    {"_rspdlite_error_", (DL_FUNC) &_rspdlite_error_, 1},
    {"_rspdlite_critical_", (DL_FUNC) &_rspdlite_critical_, 1},
    {"_rspdlite_set_level_", (DL_FUNC) &_rspdlite_set_level_, 1},
    {"_rspdlite_get_level_", (DL_FUNC) &_rspdlite_get_level_, 0},
    {"_rspdlite_set_name_", (DL_FUNC) &_rspdlite_set_name_, 1},
    {"_rspdlite_get_name_", (DL_FUNC) &_rspdlite_get_name_, 0},
    {"_rspdlite_cppstandard", (DL_FUNC) &_rspdlite_cppstandard, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rspdlite(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
