# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple Pass-Through Formatter to \code{fmt::format()}
#'
#' The C-level interface of R does not make it easy to pass \code{...}  arguments.
#' This helper function assumes it has already been called with \code{format()}
#' on each argument (as a wrapper can do) so it just spreads out the class to
#' \code{fmt::format{}} which, being C++, uses variadic templates to receive the
#' arguments. The main motivation for this function to able to format string as
#' use by the \sQuote{fmtlib::fmt} library included in \sQuote{spdlog} to write
#' similar debug strings in both R and C++. This function permits R calls with
#' multiple arguments of different types which (by being formatted on the R side)
#' are handled as strings (whereas C++ logging has access to the templating logic).
#'
#' @param s A character variable with a format string for \sQuote{fmtlib::fmt}
#' @param v A character vector with the logging string arguments.
#' @return A single (formatted) string
#' @seealso https://github.com/fmtlib/fmt
formatter <- function(s, v) {
    .Call(`_rspdlite_formatter`, s, v)
}

trace_ <- function(s) {
    invisible(.Call(`_rspdlite_trace_`, s))
}

debug_ <- function(s) {
    invisible(.Call(`_rspdlite_debug_`, s))
}

info_ <- function(s) {
    invisible(.Call(`_rspdlite_info_`, s))
}

warn_ <- function(s) {
    invisible(.Call(`_rspdlite_warn_`, s))
}

error_ <- function(s) {
    invisible(.Call(`_rspdlite_error_`, s))
}

critical_ <- function(s) {
    invisible(.Call(`_rspdlite_critical_`, s))
}

set_level_ <- function(s) {
    invisible(.Call(`_rspdlite_set_level_`, s))
}

get_level_ <- function() {
    .Call(`_rspdlite_get_level_`)
}

set_name_ <- function(s) {
    invisible(.Call(`_rspdlite_set_name_`, s))
}

get_name_ <- function() {
    .Call(`_rspdlite_get_name_`)
}

cppstandard <- function() {
    .Call(`_rspdlite_cppstandard`)
}

